//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvonessaMVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Categories1 = new HashSet<Category>();
            this.Products = new HashSet<Product>();
        }
    
        public int C_Id { get; set; }
        public Nullable<int> C_C_Id { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> OrderInPage { get; set; }
        public Nullable<int> I_I_Id { get; set; }
        public string CategoryNameEnglish { get; set; }
    
        public virtual ICollection<Category> Categories1 { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual Image Image { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
