//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvonessaMVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrder
    {
        public int CO_Id { get; set; }
        public int CR_CR_Id { get; set; }
        public int O_O_Id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
