//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvonessaMVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.CustomerOrders = new HashSet<CustomerOrder>();
            this.OrderProducts = new HashSet<OrderProduct>();
            this.tblPostLinkDatas = new HashSet<tblPostLinkData>();
        }
    
        public int O_Id { get; set; }
        public System.DateTime O_Date { get; set; }
        public short O_IsPaid { get; set; }
        public string O_Payment_date { get; set; }
        public string O_Transaction { get; set; }
        public string O_PaymentId { get; set; }
        public string O_PayerId { get; set; }
    
        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual ICollection<tblPostLinkData> tblPostLinkDatas { get; set; }
    }
}
