//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvonessaMVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
            this.ShoppingBagProducts = new HashSet<ShoppingBagProduct>();
        }
    
        public int P_Id { get; set; }
        public decimal ProductCost { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> I_I_Id { get; set; }
        public int C_C_Id { get; set; }
        public string Notes { get; set; }
        public string ProductNameEnglish { get; set; }
        public string NotesEnglish { get; set; }
        public Nullable<int> ProductInStock { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Image Image { get; set; }
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual ICollection<ShoppingBagProduct> ShoppingBagProducts { get; set; }
    }
}
