//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvonessaMVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingBag
    {
        public ShoppingBag()
        {
            this.ShoppingBagProducts = new HashSet<ShoppingBagProduct>();
        }
    
        public int SB_Id { get; set; }
        public System.DateTime SB_Date { get; set; }
    
        public virtual ICollection<ShoppingBagProduct> ShoppingBagProducts { get; set; }
    }
}
